# Generated by Django 4.2.16 on 2024-11-23 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('button_text_primary', models.CharField(max_length=50)),
                ('button_text_secondary', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero_images/')),
                ('hero_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.herosection')),
            ],
        ),
    ]
