# Generated by Django 4.2.16 on 2024-11-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='offer_section_images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(max_length=7)),
            ],
        ),
    ]
